### ISSUE TITLE
Is the input dimension of Score 256 when QAM is used in STCN?

### ISSUE THREAD

**Issue by lzl2040** [workforai/QDMN#1]

**Comment by workforai** [comment]
The input feature is the value feature after fuser, with the dimension of 512

**Comment by lzl2040** [comment]
ok,thank you

**Comment by lzl2040** [comment]
> The input feature is the value feature after fuser, with the dimension of 512
您好,当我将QAM加入到STCN当中时,且输入到Score模块的特征是fuse后的,但是训练得到的score值到后面都是0了.我是1GPU训练,batch size为16,学习率为1e-5
