### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by karchen-geng** [workforai/QDMN#10]
您好，我想问一下，stage-0 是静态图片，这个静态图片的数据集是哪一个呢？stage-1是BL30k，这个数据集的处理和davis是一致的嘛？

**Comment by workforai** [comment]
Hi, following MiVOS, the static datasets we used are the combination of DUTS, HRSOD, FSS, ECSSD, and BIG. You can prepare them according to the instructions in the data preparation part. BL30K is a large-scale synthetic dataset. The augmentation of BL30K is basically the same as DAVIS except for the cropping scheme.

**Comment by karchen-geng** [comment]
您好，我想问一下在训练的时候，所用的youtube 2019数据集时all_frames嘛

**Comment by workforai** [comment]
No
