### ISSUE TITLE
youtube2018

### ISSUE THREAD

**Issue by karchen-geng** [workforai/QDMN#14]
您好，请问如何对youtube2018的结果进行评估，您所提供的链接失效，无法进行评估？
![图片](https://github.com/workforai/QDMN/assets/81698409/37b23fdc-7c35-44c4-9fc3-f270b0dad69c)

**Comment by yongliu20** [comment]
The official has deprecated the original testing link, this is the new testing link: https://codalab.lisn.upsaclay.fr/competitions/7685#results

**Comment by karchen-geng** [comment]
thanks a lot!
