### ISSUE TITLE
Adding QAM only in STM's inference stage

### ISSUE THREAD

**Issue by csustYyh** [workforai/QDMN#15]
您好，感谢您的这项出色的工作！
我现在在复现论文中所说的将QAM仅用于STM的测试阶段，但是有如下困惑，希望您能不吝指教：
1.将QAM用于STM测试阶段时，记忆池更新机制是否也要使用？
2.是对每一视频帧都用QAM计算其质量得分＞0.8即可，还是像您代码中那样，至少间隔5帧再判断？
![do_pass](https://github.com/workforai/QDMN/assets/118873316/ec78c68c-769a-42cd-b90f-4c0bb27c9bcb)

**Comment by MrHsj** [comment]
你好，能咨询下你这两个问题怎么处理的吗？
