### ISSUE TITLE
I use QAM for training, the number of iterations is 75K, but the loss only drops to about 0.5, is this normal?And how much does the final loss value of the original code drop?

### ISSUE THREAD

**Issue by lzl2040** [workforai/QDMN#2]

**Comment by workforai** [comment]
Does the loss here refer to the total loss? Sorry, I can't remember the exact value. But 0.5 seems to be within the normal range. Is the 75k here the last stage? If so, maybe you can test the corresponding results after training.

**Comment by lzl2040** [comment]
OK, thanks a lot. It's a total loss. I try the effect of the model

**Comment by lzl2040** [comment]
> Does the loss here refer to the total loss? Sorry, I can't remember the exact value. But 0.5 seems to be within the normal range. Is the 75k here the last stage? If so, maybe you can test the corresponding results after training.

In fact, there is another question, why is the value of score always 0 in the first stage of training process?

**Comment by workforai** [comment]
This is not a normal phenomenon, you can check your code

**Comment by lzl2040** [comment]
> This is not a normal phenomenon, you can check your code

But when I use your code to run the first stage, the score is also 0, and the number of iterations is 10K, which is very strange

**Comment by lzl2040** [comment]
> This is not a normal phenomenon, you can check your code

The FC layer in QAM in the paper uses the sigmoid function. Why is Relu used in the code? Is it better?

**Comment by workforai** [comment]
I run the first training stage with my code. Now the iteration is 7k and the score loss is about 0.7. There is no situation where score loss is always 0.  The current code was re-implemented by me and there may be some inconsistencies, but I don't think this will cause a big difference.

**Comment by workforai** [comment]
<img width="485" alt="截屏2022-11-08 下午1 04 14" src="https://user-images.githubusercontent.com/72915904/200479566-b04f5e83-8cbe-4da5-9d90-b9256c399ca7.png">

**Comment by lzl2040** [comment]
In fact, the score mentioned above refers to the score obtained through QAM, not the score loss. When I debugged, I found that it was always 0 at the back. The loss I run is also not 0

**Comment by workforai** [comment]
Sure, there is something wrong here, when using relu, the score is always 0. What you said above is correct, I change the activation function to sigmoid and the output score is normal now. This is something I didn't notice when I re-implemented the code, thanks for discovering this problem.

**Comment by workforai** [comment]
I have fixed this issue. Since the current code was re-implemented after my internship ended, there may be some inconsistencies. Thanks again for finding this issue!

**Comment by lzl2040** [comment]
ok,ok,thank you!
