### ISSUE TITLE
您好,当我将QAM加入到STCN当中时,且输入到Score模块的特征是fuse后的,但是训练得到的score值到后面都是0了(Score模块里面全连接层的激活函数一个是relu,一个是sigmoid)我是1GPU训练,batch size为16,学习率为1e-5

### ISSUE THREAD

**Issue by lzl2040** [workforai/QDMN#7]

**Comment by workforai** [comment]
都用sigmoid试一下？原版QAM使用的都是sigmoid。也可以检查一下你加到STCN里时gt的iou等处是否存在bug

**Comment by TianXuXiang** [comment]
> Have you solved this problem？ I also meet it): when i pretrain on static s0. Here is my mask_score and gt_score ![image](https://user-images.githubusercontent.com/57097883/227485116-4ddcfed5-07d9-4f42-9a21-a7eb246b660d.png) did the sigmoid work?

你好，这是怎么跑起来的，可以请教一下吗

**Comment by 1359347500cwc** [comment]
> > Have you solved this problem？ I also meet it): when i pretrain on static s0. Here is my mask_score and gt_score ![image](https://user-images.githubusercontent.com/57097883/227485116-4ddcfed5-07d9-4f42-9a21-a7eb246b660d.png) did the sigmoid work?
> 
> 你好，这是怎么跑起来的，可以请教一下吗

原版的QDMN的我没跑过，我是把他的模块加到STCN上面的

**Comment by TianXuXiang** [comment]
> > > Have you solved this problem？ I also meet it): when i pretrain on static s0. Here is my mask_score and gt_score ![image](https://user-images.githubusercontent.com/57097883/227485116-4ddcfed5-07d9-4f42-9a21-a7eb246b660d.png) did the sigmoid work?
> > 
> > 
> > 你好，这是怎么跑起来的，可以请教一下吗
> 
> 原版的QDMN的我没跑过，我是把他的模块加到STCN上面的

OK,谢谢

**Comment by lzl2040** [comment]
> 

我之前跑的时候就是用sigmoid的

**Comment by MrHsj** [comment]
> > > Have you solved this problem？ I also meet it): when i pretrain on static s0. Here is my mask_score and gt_score ![image](https://user-images.githubusercontent.com/57097883/227485116-4ddcfed5-07d9-4f42-9a21-a7eb246b660d.png) did the sigmoid work?
> > 
> > 
> > 你好，这是怎么跑起来的，可以请教一下吗
> 
> 原版的QDMN的我没跑过，我是把他的模块加到STCN上面的

能请教一下怎么加的吗？太菜了，想学习一下
