### ISSUE TITLE
train.py启动问题

### ISSUE THREAD

**Issue by karchen-geng** [workforai/QDMN#9]
您好，请问单GPU情况下，您给出的train.py启动方式中，参数值需要怎么改？

**Comment by TianXuXiang** [comment]
> 您好，请问单GPU情况下，您给出的train.py启动方式中，参数值需要怎么改？

你好，这个解决了吗，我也想知道，可以交流一下吗

**Comment by karchen-geng** [comment]
> 

# CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1234 --nproc_per_node=1 train.py --id stage02-QNMN --stage 2 --load_network saves/QNMN_160000.pth


这是我的启动命令

**Comment by TianXuXiang** [comment]
> > 
> 
> # CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1234 --nproc_per_node=1 train.py --id stage02-QNMN --stage 2 --load_network saves/QNMN_160000.pth
> 这是我的启动命令

谢谢，现在这个torch.distributed.launch还能用吗，这显示Warning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.

**Comment by karchen-geng** [comment]
> > > 
> > 
> > 
> > # CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1234 --nproc_per_node=1 train.py --id stage02-QNMN --stage 2 --load_network saves/QNMN_160000.pth
> > 这是我的启动命令
> 
> 谢谢，现在这个torch.distributed.launch还能用吗，这显示Warning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.

这个我也不太清楚，由于我是单卡，没有处理这个warning。

**Comment by TianXuXiang** [comment]
> > > > 
> > > 
> > > 
> > > # CUDA_VISIBLE_DEVICES=0 OMP_NUM_THREADS=4 python -m torch.distributed.launch --master_port 1234 --nproc_per_node=1 train.py --id stage02-QNMN --stage 2 --load_network saves/QNMN_160000.pth
> > > 这是我的启动命令
> > 
> > 
> > 谢谢，现在这个torch.distributed.launch还能用吗，这显示Warning: The module torch.distributed.launch is deprecated and will be removed in future. Use torchrun.
> 
> 这个我也不太清楚，由于我是单卡，没有处理这个warning。

好滴，谢谢你
